services:
  app: &app
    image: yeetlight:latest
    build: .
    init: true
    ports:
      - "8080:8080"
  app-arm64:
    <<: *app
    platform: arm64
    profiles:
      - arm64
  test:
    image: rust:1.78.0
    volumes:
      - type: bind
        source: .
        target: /src
        read_only: true
    working_dir: /src
    environment:
      CARGO_TARGET_DIR: /target
    command: ["cargo", "test", "--all-targets"]
    profiles:
      - test
